### ISSUE TITLE
Support for Angular 18

### ISSUE THREAD

**Issue by webpreneur** [angular-architects/ngrx-toolkit#51]
I would like to request support for Angular 18 in the NgRx Toolkit. 

Currently, I am unable to upgrade to Angular 18 because I rely on the NgRx Toolkit, which does not support this version yet.

**Comment by rainerhahnekamp** [comment]
@webpreneur, I've removed the dependency to angular because it is transitive (via NgRx Signals). Unfortunately, we are still waiting for the release of NgRx 18. Therefore you have to install the toolkit in the same way as mentioned here: https://github.com/ngrx/platform/issues/4352

```bash
npm i @angular-architects/ngrx-toolkit --legacy-peer-deps
```

As soon as NgRx 18 is ready, we will follow along.
